version: "3.7"

services:
  eregold-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-complete
    container_name: eregold-backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - eregold-network
    depends_on:
      - eregold-session

  eregold-frontend:
    build: ./frontend
    container_name: eregold-frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    networks:
      - eregold-network

  eregold-session:
    image: redis:6.2-alpine
    container_name: eregold-session
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache-volume:/data
    networks:
      - eregold-network

  eregold-db:
    image: postgres:14.0-alpine
    container_name: eregold-db
    environment:
      POSTGRES_DB: eregold_db
      POSTGRES_USER: eregold_user
      POSTGRES_PASSWORD: eregold_pass
    ports:
      - "2345:5432"
    volumes:
      - ./database/data-dump/volume:/var/lib/postgresql/data/
    networks:
      - eregold-network

  eregold-db-migration:
    build:
      context: ./database/schema
      dockerfile: Dockerfile-complete
      network: host
    container_name: eregold-db-migration
    volumes:
      - ./database/schema:/temp
    entrypoint: ["mvn", "flyway:migrate"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2345" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: "host"

networks:
  eregold-network:
    driver: bridge

volumes:
  cache-volume:
    driver: local